### ISSUE TITLE
Crash on iPod touch 5G, iPhone 4S, and iPad 2 with iOS 9

### ISSUE THREAD

**Issue by mkalmes** [GuJEMSAdTech/gujemsiossdk#10]
We expirienced a crash of our app at startup after upgrading the dependencies of `gujemsiossdk`:

* `Google-Mobile-Ads-SDK` from 7.16.0 to 7.18.0
* `GoogleAds-IMA-iOS-SDK-For-AdMob` from 3.3.1 to 3.4.1

The crash happens during the dynamic linking of the framework: 

```
Dyld Error Message:
Dyld Message: Library not loaded: @rpath/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds
  Referenced from: /var/containers/Bundle/Application/<id>/<app name>.app/<app>
  Reason: image not found
  Dyld Version: 390.7
```

We noticed two changes. First, Google moved their internal libs from `Pods/GoogleAds-IMA-iOS-SDK-For-AdMob/GoogleInteractiveMediaAds/GoogleInteractiveMediaAds-GoogleIMA3ForAdMob/GoogleInteractiveMediaAds.framework/` to `Pods/GoogleAds-IMA-iOS-SDK-For-AdMob/GoogleInteractiveMediaAds/GoogleInteractiveMediaAds.framework/`. Second, Google deprecated `GoogleAds-IMA-iOS-SDK-For-AdMob` and recomends to use `GoogleAds-IMA-iOS-SDK`. Maybe these changes are related.

We rolled the dependencies back to their prior version as a workaround.

If you need anything else, don't hesitate to contact me.

**Comment by thomaslange** [comment]
⚠️ With the new CocoaPod version **3.1.12** this problem still exists and is blocking a pod update for every app that supports iOS 9. ⚠️

When will this problem be fixed? My live deployment is blocked as long as this bug is at hand.
