### ISSUE TITLE
AdUrl, and onClick call back

### ISSUE THREAD

**Issue by digitalhobo** [GuJEMSAdTech/gujemsiossdk#16]
Hi
Is their a way to detect if the user has tapped an interstitial.

Also Is their a way to get the add url.

We would like to show an alert before the user is redirected to the Add website.

Thanks in advance.

**Comment by daniel-gerold** [comment]
Regarding ad url: no, as the click url behind the ad creative is not the advertiser landingpage itself but the user will be redirect through some "click commands" counting the click (various HTTP 30x redirects) before hitting the final landing page. So you will not be able to retrieve the final url.

Regarding interstitial: will get back to you with this @michaelgohl ?

For which publisher are you developing/integrating ads?

**Comment by michaelgohl** [comment]
No, there isn't an event which is called on "interstitial" click

For which publisher are you developing/integrating ads?
