### ISSUE TITLE
TeadsSDK - No Code Signing

### ISSUE THREAD

**Issue by mrgrauel** [GuJEMSAdTech/gujemsiossdk#6]
Guten Morgen,

nur als Hinweis aktuell kann keine Version mit dem TeadsSDK.framework und TeadsSDKResource.bundle zu Apple eingereicht werden.

> ERROR ITMS-90166: "Missing Code Signing Entitlements. No entitlements found in bundle 'tv.teads.TeadsSDKResources' for executable 'Payload/Chefkoch.app/TeadsSDKResources.bundle/TeadsSDKResources'.""

**Comment by giniedp** [comment]
+1

**Comment by mbruegmann** [comment]
Sollte mit release 3.1.4 vom 8. April 2016 gefixt sein.
Wir haben eine neue Version des Teads SDK (2.0.3) integriert, die folgenden Fix (aus 2.0.2) enthält:
_Fixed ERROR ITMS-90166 that might appear when submitting app to iTunes Connect_

siehe: https://github.com/teads/TeadsSDK-iOS#changelog

**Comment by giniedp** [comment]
danke. Kann bestätigen dass es mit 3.1.5 funktioniert
